### PR TITLE
Export TypeScript library declarations

### PR DESCRIPTION
**Pull request by rrthomas**

### CODE REVIEW

**Comment by rrthomas** [comment]
Thanks! It would be nice to do the same for the `install` usage, but I couldn't work out how to do that.

**Comment by rauschma** [comment]
Ah, I had overlooked that! I switched to "typesVersions" – which supports multiple files and has worked for me in the past. Does that fix the issues you are having?

Related discussion: https://fosstodon.org/@rauschma/110967143576572537

**Comment by rrthomas** [comment]
Ah, that should do it, thanks! I found it surprisingly hard to find documentation for how to add multiple types files to `package.json`, only finding an open issue for a request to add support for multiple files to the `types` item. I didn't comes across `typesVersions`.

**Comment by rauschma** [comment]
FWIW—this is my blog post on this topic: https://2ality.com/2021/06/typescript-esm-nodejs.html

**Comment by rrthomas** [comment]
Ah, it was your blog I was reading about the `Set` extension too then! Thanks for that also.

**Pull request merged**
